[build-system]
requires = [
  # scikit-build-core drives CMake + Ninja
  "scikit-build-core>=0.9.3",
  # used only at sdist-time, writes src/fpm/_version.py
  "setuptools_scm>=8",
  "cmake>=3.25",
  "ninja"
]
build-backend = "scikit_build_core.build"

[project]
name = "fpm"
license = { text = "MIT License" }
authors = [{ name = "fpm maintainers" }]
requires-python = ">=3.7"
description = "Fortran package manager"
readme = "docs/README.md"
keywords = ["fpm", "fortran", "package manager"]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent",
  "Programming Language :: Fortran",
  "Topic :: Software Development :: Build Tools",
  "Topic :: Software Development :: Compilers",
  "Topic :: Software Development :: Pre-processors",
  "Topic :: Utilities",
]
dynamic = ["version", "entry-points", "scripts"]

[project.urls]
homepage = "https://fpm.fortran-lang.org"
source-code = "https://github.com/fortran-lang/fpm"
bug-tracker = "https://github.com/fortran-lang/fpm/issues"

[tool.setuptools_scm]
write_to = "src/fpm/_version.py"

[tool.cibuildwheel]
build = "cp39-* cp310-* cp311-* cp312-*"
build-verbosity = "3"

[tool.cibuildwheel.macos]
archs = ["universal2"]
before-build = "bash {project}/tools/wheels/install_gfortran_conda.sh"
environment = { CC = "clang", CXX = "clang++", FC = "gfortran", MACOSX_DEPLOYMENT_TARGET = "11.0", CONDA_DEFAULT_ENV = "base"}

#[tool.cibuildwheel.windows]
#archs = ["auto64"]
#environment = { CC = "gcc", CXX = "g++", FC = "gfortran", CONDA_DEFAULT_ENV = "base" }

# --- Linux ---------------------------------------------------------------
# 100 % pure; no special tool-chain needed

# --- Windows -------------------------------------------------------------
# FPM is a CLI; skip Windows for now (re-enable when a working gfortran exists)
skip = "*-win_*"
